# Generated by Django 5.1.2 on 2024-10-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('landlord', 'landlord'), ('tenant', 'tenant'), ('user', 'user')], default='user', help_text="Role either: 'user','landlord' or 'tenant'.", max_length=10),
        ),
    ]
