# Generated by Django 5.1.2 on 2024-10-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_email_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(blank=True, help_text='Email address of the user.', max_length=255, null=True, unique=True),
        ),
    ]
