# Generated by Django 5.1.2 on 2024-10-23 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_customuser_role_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landlordtenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
