
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: landlord_db
      POSTGRES_USER: landlord_user
      POSTGRES_PASSWORD: landlord_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app  # Mounts the current directory into the container
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
